// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e5c3c800-a20e-43e7-b722-0aca8ecb045e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLed1Change();
void onRele1Change();
void onRele2Change();
void onRele3Change();

bool led1;
bool rele1;
bool rele2;
bool rele3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);
  ArduinoCloud.addProperty(rele1, READWRITE, ON_CHANGE, onRele1Change);
  ArduinoCloud.addProperty(rele2, READWRITE, ON_CHANGE, onRele2Change);
  ArduinoCloud.addProperty(rele3, READWRITE, ON_CHANGE, onRele3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
