#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f6baa900-4b88-4df6-905b-72b5cf353f18 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool led1;
  bool rele1;
  bool rele2;
  bool rele3;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int ledPin1 = D0;
const int ledPin2 = D1;
const int ledPin3 = D2;
const int ledPin4 = D3;

void setup() {
  pinMode(ledPin1, OUTPUT);
  pinMode(ledPin2, OUTPUT);
  pinMode(ledPin3, OUTPUT);
  pinMode(ledPin4, OUTPUT);
  
  Serial.begin(9600);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  onLed1Change();
  onRele1Change();
  onRele2Change();
  onRele3Change();
}

void onLed1Change()  {
  if (led1) {
    digitalWrite(ledPin1, HIGH); // Ligue o LED 
    delay(1000); // Aguarde 1 segundo 
    digitalWrite(ledPin1, LOW); // Desligue o LED 
    delay(1000); // Aguarde 1 segundo
  } else {
    digitalWrite(ledPin1, LOW); // Desligue o LED 
  }
}

void onRele1Change()  {
  if (rele1) {
    digitalWrite(ledPin2, HIGH); // Ligue o LED 
    delay(1000); // Aguarde 1 segundo 
    digitalWrite(ledPin2, LOW); // Desligue o LED 
    delay(1000); // Aguarde 1 segundo
  } else {
    digitalWrite(ledPin2, LOW); // Desligue o LED 
  }
}

void onRele2Change()  {
  if (rele2) {
    digitalWrite(ledPin3, HIGH); // Ligue o LED 
    delay(1000); // Aguarde 1 segundo 
    digitalWrite(ledPin3, LOW); // Desligue o LED 
    delay(1000); // Aguarde 1 segundo
  } else {
    digitalWrite(ledPin3, LOW); // Desligue o LED 
  }
}

void onRele3Change()  {
  if (rele3) {
    digitalWrite(ledPin4, HIGH); // Ligue o LED 
    delay(1000); // Aguarde 1 segundo 
    digitalWrite(ledPin4, LOW); // Desligue o LED 
    delay(1000); // Aguarde 1 segundo
  } else {
    digitalWrite(ledPin4, LOW); // Desligue o LED 
  }
}