// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8f4af089-c6d4-4ce2-8ff3-059d937c57af";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedD0Change();
void onLedD1Change();
void onLedD2Change();
void onLedD3Change();
void onLedD4Change();

bool led_D0;
bool led_D1;
bool led_D2;
bool led_D3;
bool led_D4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led_D0, READWRITE, 1 * SECONDS, onLedD0Change);
  ArduinoCloud.addProperty(led_D1, READWRITE, 1 * SECONDS, onLedD1Change);
  ArduinoCloud.addProperty(led_D2, READWRITE, 1 * SECONDS, onLedD2Change);
  ArduinoCloud.addProperty(led_D3, READWRITE, 1 * SECONDS, onLedD3Change);
  ArduinoCloud.addProperty(led_D4, READWRITE, 1 * SECONDS, onLedD4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
